language: python
python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7-dev'
    - 'pypy'
    - 'pypy-5.3.1'

services:
    - docker

before_install:
    - pip install codecov
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get --yes install docker-ce
    # allow ARM builds with QEMU
    - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
    - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register

install:
    - pip install .
    - pip install -r requirements-dev.txt

after_success:
    - codecov

env:
    - W1THERMSENSOR_NO_KERNEL_MODULE=1

script:
    - coverage run --source w1thermsensor -m pytest tests/unit/ -s
    - coverage report
    - flake8 --show-source w1thermsensor/ tests/unit/

jobs:
    include:
        - stage: Raspbian integration tests
          sudo: required
          install:
              - docker version
              - make travis-prepare-integration
          script:
              - make travis-integration-tests
              - ls -l deb/
          # we don't need this env variable
          env: W1THERMSENSOR_NO_KERNEL_MODULE=None
          deploy:
              provider: releases
              api_key:
                secure: IAzzKHT/Hckgwz07wL/oEyvNraPPUHVd/JAD2U7bgZGg0zAEnM6A14OK7XrRh2DBuvgSemlFosxiE6W8baBT0qGrP6kQ1zXo9FghohFJxG1yeCB0YKWmRPJOtY191U9XdyTv9kOFHiFR5xMGaAXBNz/zjn9dHAKLDITz7RDUaQI=
              file_glob: true
              file: deb/*.deb
              skip_cleanup: true
              on:
                tags: true
                repo: timofurrer/w1thermsensor
    #allow_failures:
        #- stage: Raspbian integration tests

notifications:
    webhooks:
    urls:
        - https://webhooks.gitter.im/e/1783c332a0ad247e3476
    on_success: always
    on_failure: always
    on_start: false

addons:
    code_climate:
        repo_token: ff2793d6c31bf4cf431c7f57cca9c745679f16d8c6a7fd78b1c0ca5ec1c68473

deploy:
    provider: pypi
    user: tuxtimo
    password:
        secure: Eo0i4i7qHgFcLWbLX/dM3DsGZzOBOj3z1KxqjjUt14uUd0Kz1S3kpTmRo63CT44gQSP0C3pFGwa3h7yv07wryO9c/OtHC+c0H+6ZE8GO4o/sMTPFp44jIbS4dpx6PAYwxs8ZO9DaK9dCm5y5re1ynUrC+mA488yjFaQM8oRKnDg=
    on:
        branch: master
        tags: true
        repo: timofurrer/w1thermsensor
    distributions: sdist bdist_wheel
    skip_cleanup: true
